"""
scraper/seed.py

Inserta datos de personajes reales para poder probar la API
inmediatamente sin necesidad de hacer scraping completo.

Incluye 56 personajes de Dragon Ball Z Dokkan Battle
cubriendo todas las rarezas (N, R, SR, SSR, UR, LR) y
todos los tipos (AGL, TEQ, INT, STR, PHY).

Para obtener TODOS los personajes del juego (miles de cartas),
usa los endpoints de sincronizacion tras arrancar la API:
    POST /sync/cards/rarity/LR?max_cards=300
    POST /sync/cards/rarity/UR?max_cards=300
    POST /sync/run-now

Ejecutar: python -m scraper.seed
"""

import sys
import os
import json

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.database import SessionLocal, init_db
from app.models.card import Card
from app.models.event import Event
from app.models.banner import Banner
from app.models.item import Item

SAMPLE_CARDS = [
    {
        "wiki_id": "Ultra_Instinct_Goku",
        "name": "Goku (Ultra Instinct)",
        "title": "Transcendent Instinct",
        "full_name": "Transcendent Instinct Goku (Ultra Instinct)",
        "rarity": "LR",
        "type": "AGL",
        "cost": 59,
        "hp_max": 22428,
        "atk_max": 24000,
        "def_max": 14000,
        "leader_skill": "All Types Ki +4, HP, ATK & DEF +170%",
        "super_attack": "Godly Display - Raises ATK & DEF, causes mega-colossal damage",
        "passive_skill": "Power Without Limits - Ki +5, ATK +200% and DEF +150%; attacks become critical after 8+ attacks",
        "categories": "[\"God Ki\", \"Pure Saiyans\", \"Kamehameha\", \"Goku's Family\", \"Ultra Instinct\", \"Gifted Warriors\"]",
        "link_skills": "[\"Super Saiyan\", \"Kamehameha\", \"Golden Warrior\", \"Prepared for Battle\", \"Over in a Flash\", \"Universe's Most Powerful\"]",
        "is_lr": True,
        "is_eza": True,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Transcendent_Instinct_-Sign-_Goku_(Ultra_Instinct)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014450_thumb.png/120px-Card_1014450_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014450_thumb.png/60px-Card_1014450_thumb.png",
        "hp_eza": 26428,
        "atk_eza": 28000,
        "def_eza": 17000,
        "ultra_super_attack": "Surpassing All - Raises ATK, lowers DEF, mega-colossal damage to all enemies",
        "active_skill": "Mastered Ultra Instinct - 7 critical hits, all enemies DEF -100% for 3 turns",
        "active_skill_condition": "Can be activated when 20 or more Ki Spheres are obtained in battle",
        "eza_leader_skill": "All Types Ki +4, HP, ATK & DEF +200%",
        "eza_passive_skill": "Power Without Limits - Ki +5, ATK +230% and DEF +180%; attacks become critical",
        "awakening_medals": "[{\"name\": \"Ultra Instinct Goku Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Super_Saiyan_Bardock_LR",
        "name": "Bardock (Super Saiyan)",
        "title": "Lone Warrior's Rebellion",
        "full_name": "Lone Warrior's Rebellion Bardock (Super Saiyan)",
        "rarity": "LR",
        "type": "AGL",
        "cost": 59,
        "hp_max": 19650,
        "atk_max": 22100,
        "def_max": 12500,
        "leader_skill": "AGL Type Ki +4, HP, ATK & DEF +170%; additional HP, ATK & DEF +30% for Pure Saiyans Category",
        "super_attack": "Rebellion Spear - Mega-colossal damage with a chance of stunning the enemy",
        "passive_skill": "Proof of Rebellion - Ki +5, ATK & DEF +180%; performs an additional attack",
        "categories": "[\"Pure Saiyans\", \"Terrifying Conquerors\", \"Saviors\", \"Otherworld Warriors\", \"Bond of Parent and Child\"]",
        "link_skills": "[\"Super Saiyan\", \"Prepared for Battle\", \"Saiyan Warrior Race\", \"Z Fighters\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Super_Saiyan_Bardock",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1015850_thumb.png/120px-Card_1015850_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1015850_thumb.png/60px-Card_1015850_thumb.png",
        "hp_eza": 23000,
        "atk_eza": 26000,
        "def_eza": 15000,
        "ultra_super_attack": "Final Spirit Cannon - Mega-colossal damage to enemy and raises ATK",
        "awakening_medals": "[{\"name\": \"Bardock Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Goku_Frieza_Final_Showdown_LR",
        "name": "Goku & Frieza (Final Showdown)",
        "title": "The Greatest Rivals",
        "full_name": "The Greatest Rivals Goku & Frieza (Final Showdown)",
        "rarity": "LR",
        "type": "AGL",
        "cost": 59,
        "hp_max": 20200,
        "atk_max": 22600,
        "def_max": 13400,
        "leader_skill": "AGL Type Ki +4, HP, ATK & DEF +170%",
        "super_attack": "Final Kamehameha - Raises ATK & DEF, mega-colossal damage to all enemies",
        "passive_skill": "Miraculous Combination - Ki +5, ATK & DEF +180%; stacks ATK +30% per Super Attack",
        "categories": "[\"Pure Saiyans\", \"Wicked Bloodline\", \"Universe's Most Powerful\", \"Rivals\"]",
        "link_skills": "[\"Kamehameha\", \"Universe's Most Powerful\", \"Prepared for Battle\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_%26_Frieza_(Final_Showdown)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1016350_thumb.png/120px-Card_1016350_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1016350_thumb.png/60px-Card_1016350_thumb.png",
        "ultra_super_attack": "True Final Kamehameha - Mega-colossal damage to all enemies and greatly lowers DEF",
        "awakening_medals": "[{\"name\": \"Final Showdown Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Gohan_Beast_LR",
        "name": "Gohan (Beast)",
        "title": "Awakened Beast",
        "full_name": "Awakened Beast Gohan (Beast)",
        "rarity": "LR",
        "type": "TEQ",
        "cost": 59,
        "hp_max": 20500,
        "atk_max": 22800,
        "def_max": 13100,
        "leader_skill": "TEQ Type Ki +4, HP, ATK & DEF +170%; additional ATK & DEF +30% for Goku's Family Category",
        "super_attack": "Perfected Evolution Kamehameha - Raises ATK, mega-colossal damage to all enemies and lowers ATK & DEF",
        "passive_skill": "Absolute Power - Ki +5, ATK & DEF +200%; launches an additional attack",
        "categories": "[\"Hybrid Saiyans\", \"Goku's Family\", \"Kamehameha\", \"Galactic Patrol\", \"Inhuman Deeds\"]",
        "link_skills": "[\"Kamehameha\", \"Super Saiyan\", \"Prepared for Battle\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Gohan_(Beast)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1019300_thumb.png/120px-Card_1019300_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1019300_thumb.png/60px-Card_1019300_thumb.png",
        "ultra_super_attack": "Beast Surge - Mega-colossal damage to all enemies; greatly lowers DEF",
        "awakening_medals": "[{\"name\": \"Beast Gohan Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "SSB_Evolved_Vegeta_LR",
        "name": "Vegeta (Super Saiyan God SS Evolved)",
        "title": "Beyond Super Saiyan God SS",
        "full_name": "Beyond Super Saiyan God SS Vegeta (Super Saiyan God SS Evolved)",
        "rarity": "LR",
        "type": "TEQ",
        "cost": 59,
        "hp_max": 21000,
        "atk_max": 23500,
        "def_max": 13800,
        "leader_skill": "TEQ Type Ki +4, HP, ATK & DEF +170%; additional ATK & DEF +30% for Pure Saiyans or Vegeta's Family Category",
        "super_attack": "Ultimate Final Flash - Raises ATK, mega-colossal damage to all enemies",
        "passive_skill": "King of Saiyans - Ki +5, ATK & DEF +200%; performs an additional Super Attack when HP is 50% or above",
        "categories": "[\"God Ki\", \"Pure Saiyans\", \"Vegeta's Family\", \"Bond of Father and Son\", \"Rival Duo\"]",
        "link_skills": "[\"Super Saiyan\", \"Golden Warrior\", \"Prepared for Battle\", \"Royal Lineage\", \"Saiyan Warrior Race\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": True,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Vegeta_(Super_Saiyan_God_SS_Evolved)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1016900_thumb.png/120px-Card_1016900_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1016900_thumb.png/60px-Card_1016900_thumb.png",
        "hp_eza": 24500,
        "atk_eza": 27500,
        "def_eza": 16500,
        "ultra_super_attack": "God Breaker - Mega-colossal damage to all enemies and lowers ATK & DEF",
        "active_skill": "Royal Final Flash - Raises own ATK & DEF, mega-colossal damage to all enemies",
        "active_skill_condition": "Can be activated when HP is 50% or above",
        "eza_leader_skill": "TEQ Type Ki +4, HP, ATK & DEF +200%",
        "eza_passive_skill": "King of Saiyans - Ki +5, ATK & DEF +230%; performs additional Super Attacks",
        "awakening_medals": "[{\"name\": \"Vegeta SSB Evolved Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Future_Gohan_Trunks_LR",
        "name": "Future Gohan & Future Trunks",
        "title": "Bonds Transcending Time",
        "full_name": "Bonds Transcending Time Future Gohan & Future Trunks",
        "rarity": "LR",
        "type": "TEQ",
        "cost": 59,
        "hp_max": 20800,
        "atk_max": 22200,
        "def_max": 14100,
        "leader_skill": "TEQ Type Ki +4, HP, ATK & DEF +160%; additional ATK & DEF +30% for Future Saga Category",
        "super_attack": "Masenko - Raises ATK, mega-colossal damage to all enemies",
        "passive_skill": "Never Give Up - Ki +5, ATK & DEF +180% when facing Extreme-type enemies",
        "categories": "[\"Future Saga\", \"Hybrid Saiyans\", \"Goku's Family\", \"Time Travelers\", \"Bond of Master and Disciple\"]",
        "link_skills": "[\"Super Saiyan\", \"Prepared for Battle\", \"Z Fighters\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Future_Gohan_%26_Future_Trunks",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1013960_thumb.png/120px-Card_1013960_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1013960_thumb.png/60px-Card_1013960_thumb.png",
        "ultra_super_attack": "Burning Attack - Mega-colossal damage to all enemies and greatly lowers ATK",
        "awakening_medals": "[{\"name\": \"Future Gohan Medal\", \"quantity\": 40}, {\"name\": \"Future Trunks Medal\", \"quantity\": 40}]"
    },
    {
        "wiki_id": "Goku_Black_Zamasu_LR",
        "name": "Goku Black (Super Saiyan Rose) & Zamasu",
        "title": "Divine Dual Elimination",
        "full_name": "Divine Dual Elimination Goku Black (Super Saiyan Rose) & Zamasu",
        "rarity": "LR",
        "type": "TEQ",
        "cost": 59,
        "hp_max": 20100,
        "atk_max": 22000,
        "def_max": 13600,
        "leader_skill": "TEQ Type Ki +4, HP, ATK & DEF +170%; additional ATK & DEF +30% for Realm of Gods Category",
        "super_attack": "Divine Retribution - Raises ATK & DEF and causes mega-colossal damage",
        "passive_skill": "Absolute Justice - Ki +5, ATK & DEF +200% when performing a Super Attack",
        "categories": "[\"Future Saga\", \"Realm of Gods\", \"God Ki\", \"Potara\", \"Wicked Bloodline\", \"Time Travelers\"]",
        "link_skills": "[\"Godly Power\", \"Prepared for Battle\", \"Power Bestowed by God\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_Black_(SSR)_%26_Zamasu",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014650_thumb.png/120px-Card_1014650_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014650_thumb.png/60px-Card_1014650_thumb.png",
        "ultra_super_attack": "God Slicer - Mega-colossal damage to all enemies; greatly lowers DEF",
        "awakening_medals": "[{\"name\": \"Goku Black & Zamasu Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Cell_Perfect_Form_LR",
        "name": "Cell (Perfect Form)",
        "title": "Ultimate Form",
        "full_name": "Ultimate Form Cell (Perfect Form)",
        "rarity": "LR",
        "type": "INT",
        "cost": 59,
        "hp_max": 19800,
        "atk_max": 22000,
        "def_max": 13000,
        "leader_skill": "INT Type Ki +4, HP, ATK & DEF +170%",
        "super_attack": "Solar Kamehameha - Mega-colossal damage to all enemies and lowers DEF",
        "passive_skill": "Perfection - Ki +5, ATK & DEF +200%; launches additional attack; absorbs damage at 30%",
        "categories": "[\"Cell Saga\", \"Androids/Cell Saga\", \"Wicked Bloodline\", \"Artificial Life Forms\", \"Inhuman Deeds\"]",
        "link_skills": "[\"Kamehameha\", \"Brutal Beatdown\", \"Prepared for Battle\", \"Power Bestowed by God\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": True,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Cell_(Perfect_Form)_LR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014300_thumb.png/120px-Card_1014300_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014300_thumb.png/60px-Card_1014300_thumb.png",
        "hp_eza": 23200,
        "atk_eza": 25800,
        "def_eza": 15700,
        "ultra_super_attack": "Perfect Kamehameha - Mega-colossal damage to all enemies; massively lowers ATK & DEF",
        "active_skill": "Full Power - Greatly raises ATK for 3 turns and causes mega-colossal damage to all enemies",
        "active_skill_condition": "Can be activated starting from the 3rd turn from the start of battle",
        "eza_leader_skill": "INT Type Ki +4, HP, ATK & DEF +200%",
        "eza_passive_skill": "Perfection - Ki +5, ATK & DEF +230%; additional attacks and 40% damage absorption",
        "awakening_medals": "[{\"name\": \"Cell (Perfect Form) Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Zamasu_Fused_LR",
        "name": "Fused Zamasu",
        "title": "Immortal Fusion of God and Man",
        "full_name": "Immortal Fusion of God and Man Fused Zamasu",
        "rarity": "LR",
        "type": "INT",
        "cost": 59,
        "hp_max": 20500,
        "atk_max": 22500,
        "def_max": 13500,
        "leader_skill": "INT Type Ki +4, HP, ATK & DEF +170%; additional ATK & DEF +30% for Potara Category",
        "super_attack": "Blades of Judgment - Mega-colossal damage to enemy and lowers DEF",
        "passive_skill": "Infinite Power - Ki +5 and ATK & DEF +200%; HP recovered by 10% at end of turn",
        "categories": "[\"Potara\", \"Future Saga\", \"God Ki\", \"Wicked Bloodline\", \"Inhuman Deeds\"]",
        "link_skills": "[\"Godly Power\", \"Prepared for Battle\", \"Power Bestowed by God\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Fused_Zamasu",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1015600_thumb.png/120px-Card_1015600_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1015600_thumb.png/60px-Card_1015600_thumb.png",
        "ultra_super_attack": "Divine Retribution - Mega-colossal damage to all enemies; greatly lowers ATK & DEF",
        "awakening_medals": "[{\"name\": \"Fused Zamasu Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "SSB_Goku_Vegeta_LR",
        "name": "Goku (SSGSS) & Vegeta (SSGSS)",
        "title": "Decisive Battle in the Realm of Gods",
        "full_name": "Decisive Battle in the Realm of Gods Goku (SSGSS) & Vegeta (SSGSS)",
        "rarity": "LR",
        "type": "INT",
        "cost": 59,
        "hp_max": 20600,
        "atk_max": 22300,
        "def_max": 13800,
        "leader_skill": "INT Type Ki +4, HP, ATK & DEF +170%; additional HP, ATK & DEF +30% for God Ki Category",
        "super_attack": "Combined God Kamehameha - Mega-colossal damage to all enemies",
        "passive_skill": "Divine Bond - Ki +5, ATK & DEF +200%; performs an additional attack per STR or AGL Ki Sphere",
        "categories": "[\"God Ki\", \"Pure Saiyans\", \"Goku's Family\", \"Vegeta's Family\", \"Rival Duo\"]",
        "link_skills": "[\"Super Saiyan\", \"Godly Power\", \"Kamehameha\", \"Golden Warrior\", \"Prepared for Battle\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_%26_Vegeta_(SSGSS)_LR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1013260_thumb.png/120px-Card_1013260_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1013260_thumb.png/60px-Card_1013260_thumb.png",
        "ultra_super_attack": "Final Kamehameha - Mega-colossal damage to all enemies; greatly lowers ATK & DEF",
        "awakening_medals": "[{\"name\": \"SSGSS Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Android_17_18_LR",
        "name": "Android 17 & Android 18",
        "title": "Two Cylinders of Perfection",
        "full_name": "Two Cylinders of Perfection Android 17 & Android 18",
        "rarity": "LR",
        "type": "INT",
        "cost": 59,
        "hp_max": 20300,
        "atk_max": 21800,
        "def_max": 14500,
        "leader_skill": "INT Type Ki +4, HP, ATK & DEF +170%; additional HP, ATK & DEF +30% for Androids/Cell Saga Category",
        "super_attack": "Accel Dance - Mega-colossal damage to all enemies and raises DEF",
        "passive_skill": "Infinite Power - Ki +5, ATK & DEF +200%; guard and counter when attacked",
        "categories": "[\"Androids/Cell Saga\", \"Artificial Life Forms\", \"Universe 7\", \"Tournament of Power\"]",
        "link_skills": "[\"Androids\", \"Prepared for Battle\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Android_17_%26_Android_18_LR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014800_thumb.png/120px-Card_1014800_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014800_thumb.png/60px-Card_1014800_thumb.png",
        "ultra_super_attack": "Dual Accel Dance - Mega-colossal damage to all enemies; greatly lowers ATK & DEF",
        "awakening_medals": "[{\"name\": \"Android Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Broly_LR_STR",
        "name": "Broly",
        "title": "Wrathful Saiyan of Destruction",
        "full_name": "Wrathful Saiyan of Destruction Broly",
        "rarity": "LR",
        "type": "STR",
        "cost": 59,
        "hp_max": 21200,
        "atk_max": 24500,
        "def_max": 12800,
        "leader_skill": "STR Type Ki +4, HP, ATK & DEF +170%; additional ATK & DEF +30% for Pure Saiyans Category",
        "super_attack": "Gigantic Roar - Raises ATK, mega-colossal damage to all enemies",
        "passive_skill": "Saiyan's Pride and Fury - Ki +5, ATK +220% and DEF +170%",
        "categories": "[\"Pure Saiyans\", \"Terrifying Conquerors\", \"Movie Heroes\", \"Gifted Warriors\"]",
        "link_skills": "[\"Prepared for Battle\", \"Saiyan Warrior Race\", \"Brutal Beatdown\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Broly_LR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1017850_thumb.png/120px-Card_1017850_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1017850_thumb.png/60px-Card_1017850_thumb.png",
        "ultra_super_attack": "Omega Blaster - Raises ATK & DEF, mega-colossal damage to all enemies",
        "active_skill": "Gigantic Meteor - Mega-colossal damage to all enemies; greatly lowers ATK & DEF",
        "active_skill_condition": "Can be activated when HP is 80% or above from the 3rd turn",
        "awakening_medals": "[{\"name\": \"Broly Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Jiren_Full_Power_LR",
        "name": "Jiren (Full Power)",
        "title": "Absolute Realm of God",
        "full_name": "Absolute Realm of God Jiren (Full Power)",
        "rarity": "LR",
        "type": "STR",
        "cost": 59,
        "hp_max": 20100,
        "atk_max": 22800,
        "def_max": 13200,
        "leader_skill": "STR Type Ki +4, HP, ATK & DEF +170%",
        "super_attack": "Power Impact - Raises ATK, mega-colossal damage to all enemies",
        "passive_skill": "Pinnacle of Strength - Ki +5, ATK & DEF +200%; guards against all attacks when HP is 50% or above",
        "categories": "[\"Universe 11\", \"Tournament of Power\", \"Gifted Warriors\", \"Universe's Most Powerful\"]",
        "link_skills": "[\"Universe's Most Powerful\", \"Prepared for Battle\", \"Brutal Beatdown\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Jiren_(Full_Power)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1016700_thumb.png/120px-Card_1016700_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1016700_thumb.png/60px-Card_1016700_thumb.png",
        "ultra_super_attack": "Overpowering Heat - Raises ATK & DEF, mega-colossal damage to all enemies",
        "awakening_medals": "[{\"name\": \"Jiren Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Majin_Vegeta_LR",
        "name": "Majin Vegeta",
        "title": "Unshakeable Saiyan Pride",
        "full_name": "Unshakeable Saiyan Pride Majin Vegeta",
        "rarity": "LR",
        "type": "STR",
        "cost": 59,
        "hp_max": 19500,
        "atk_max": 21800,
        "def_max": 12400,
        "leader_skill": "STR Type Ki +4, HP, ATK & DEF +170%; additional ATK & DEF +30% for Pure Saiyans Category",
        "super_attack": "Final Explosion - Mega-colossal damage to all enemies",
        "passive_skill": "Saiyan's Pride - Ki +5, ATK +200% and DEF +150%; immunity to stun and seal",
        "categories": "[\"Pure Saiyans\", \"Majin Buu Saga\", \"Vegeta's Family\", \"Rival Duo\", \"Bond of Father and Son\"]",
        "link_skills": "[\"Super Saiyan\", \"Golden Warrior\", \"Prepared for Battle\", \"Royal Lineage\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Majin_Vegeta_LR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1013860_thumb.png/120px-Card_1013860_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1013860_thumb.png/60px-Card_1013860_thumb.png",
        "ultra_super_attack": "Galick Gun - Mega-colossal damage to all enemies and greatly lowers ATK",
        "awakening_medals": "[{\"name\": \"Majin Vegeta LR Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Frieza_Golden_LR",
        "name": "Frieza (Golden)",
        "title": "Terror Returned to Life",
        "full_name": "Terror Returned to Life Frieza (Golden)",
        "rarity": "LR",
        "type": "PHY",
        "cost": 59,
        "hp_max": 19850,
        "atk_max": 21200,
        "def_max": 11800,
        "leader_skill": "PHY Type Ki +4 and HP, ATK & DEF +150%",
        "super_attack": "Death Beam - Mega-colossal damage to enemy and lowers DEF",
        "passive_skill": "Overwhelming Power - Ki +5, ATK +200%; counters with tremendous power when attacked",
        "categories": "[\"Wicked Bloodline\", \"Universe's Most Powerful\", \"Frieza Saga\", \"Resurrection F\"]",
        "link_skills": "[\"Universe's Most Powerful\", \"Brutal Beatdown\", \"Shocking Speed\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": False,
        "is_dokkan_fest": True,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Golden_Frieza",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014000_thumb.png/120px-Card_1014000_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014000_thumb.png/60px-Card_1014000_thumb.png",
        "ultra_super_attack": "Golden Death Beam - Mega-colossal damage to all enemies; greatly lowers DEF",
        "awakening_medals": "[{\"name\": \"Golden Frieza Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "Metal_Cooler_LR",
        "name": "Metal Cooler",
        "title": "Nightmare Reborn",
        "full_name": "Nightmare Reborn Metal Cooler",
        "rarity": "LR",
        "type": "PHY",
        "cost": 59,
        "hp_max": 19200,
        "atk_max": 21000,
        "def_max": 11500,
        "leader_skill": "PHY Type Ki +4, HP, ATK & DEF +170%; additional HP, ATK & DEF +30% for Movie Bosses Category",
        "super_attack": "Supernova Cooler - Raises ATK & DEF, mega-colossal damage to all enemies",
        "passive_skill": "Indestructible Metal Body - Ki +5, ATK & DEF +180%; automatically guards all attacks with medium chance",
        "categories": "[\"Movie Bosses\", \"Wicked Bloodline\", \"Artificial Life Forms\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Brutal Beatdown\", \"Prepared for Battle\", \"Universe's Most Powerful\", \"Fierce Battle\"]",
        "is_lr": True,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Metal_Cooler",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1015200_thumb.png/120px-Card_1015200_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1015200_thumb.png/60px-Card_1015200_thumb.png",
        "hp_eza": 22600,
        "atk_eza": 24800,
        "def_eza": 14200,
        "ultra_super_attack": "Gigantic Meteor Cooler - Mega-colossal damage to all enemies; greatly lowers ATK & DEF",
        "eza_leader_skill": "PHY Type Ki +4, HP, ATK & DEF +200%",
        "eza_passive_skill": "Indestructible Metal Body - Ki +5, ATK & DEF +210%; high chance to guard all attacks",
        "awakening_medals": "[{\"name\": \"Metal Cooler Medal\", \"quantity\": 77}]"
    },
    {
        "wiki_id": "SSJ3_Goku_UR",
        "name": "Goku (Super Saiyan 3)",
        "title": "Pinnacle of Fury",
        "full_name": "Pinnacle of Fury Goku (Super Saiyan 3)",
        "rarity": "UR",
        "type": "AGL",
        "cost": 48,
        "hp_max": 13500,
        "atk_max": 14800,
        "def_max": 7200,
        "leader_skill": "AGL Type Ki +3, HP & ATK & DEF +100%",
        "super_attack": "Super Kamehameha - Raises ATK and causes immense damage to enemy",
        "passive_skill": "Unrivaled Combat Power - Ki +5 and ATK +120% when performing a Super Attack",
        "categories": "[\"Super Saiyan 3\", \"Pure Saiyans\", \"Goku's Family\", \"Full Power\"]",
        "link_skills": "[\"Super Saiyan\", \"Kamehameha\", \"Golden Warrior\", \"Prepared for Battle\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Super_Saiyan_3_Goku_(Pinnacle_of_Fury)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1007160_thumb.png/120px-Card_1007160_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1007160_thumb.png/60px-Card_1007160_thumb.png",
        "hp_eza": 16000,
        "atk_eza": 17500,
        "def_eza": 9000,
        "eza_leader_skill": "AGL Type Ki +3, HP & ATK & DEF +130%",
        "eza_passive_skill": "Unrivaled Combat Power - Ki +5 and ATK +150% when performing a Super Attack",
        "awakening_medals": "[{\"name\": \"SSJ3 Goku Medal\", \"quantity\": 30}, {\"name\": \"Supreme Kai Medal\", \"quantity\": 15}]"
    },
    {
        "wiki_id": "SSG_Goku_UR",
        "name": "Goku (Super Saiyan God)",
        "title": "Crimson-Masked Saiyan",
        "full_name": "Crimson-Masked Saiyan Goku (Super Saiyan God)",
        "rarity": "UR",
        "type": "AGL",
        "cost": 48,
        "hp_max": 14200,
        "atk_max": 15600,
        "def_max": 8400,
        "leader_skill": "AGL Type Ki +3, HP & ATK & DEF +120%",
        "super_attack": "God Kamehameha - Raises ATK and DEF and causes immense damage to enemy",
        "passive_skill": "God Ki - ATK & DEF +120%; Ki +3 when HP is 50% or above",
        "categories": "[\"God Ki\", \"Pure Saiyans\", \"Goku's Family\", \"Realm of Gods\"]",
        "link_skills": "[\"Super Saiyan\", \"Godly Power\", \"Kamehameha\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_(Super_Saiyan_God)_AGL",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1008060_thumb.png/120px-Card_1008060_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1008060_thumb.png/60px-Card_1008060_thumb.png",
        "awakening_medals": "[{\"name\": \"SSG Goku Medal\", \"quantity\": 30}]"
    },
    {
        "wiki_id": "Kefla_UR",
        "name": "Kefla",
        "title": "Universe 6 Potara Warrior",
        "full_name": "Universe 6 Potara Warrior Kefla",
        "rarity": "UR",
        "type": "AGL",
        "cost": 48,
        "hp_max": 14600,
        "atk_max": 15900,
        "def_max": 7800,
        "leader_skill": "AGL Type Ki +3, HP & ATK & DEF +120%",
        "super_attack": "Super Kamehameha - Raises ATK and causes immense damage to all enemies",
        "passive_skill": "Potara Power - ATK & DEF +120%; Ki +3 per AGL Ki Sphere obtained",
        "categories": "[\"Universe 6\", \"Potara\", \"Pure Saiyans\", \"Tournament of Power\", \"Gifted Warriors\"]",
        "link_skills": "[\"Super Saiyan\", \"Kamehameha\", \"Golden Warrior\", \"Prepared for Battle\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Kefla_AGL",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014100_thumb.png/120px-Card_1014100_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1014100_thumb.png/60px-Card_1014100_thumb.png",
        "awakening_medals": "[{\"name\": \"Kefla Medal\", \"quantity\": 30}]",
        "is_transformable": True,
        "transformation_conditions": "Can transform when HP is 50% or above after turn 4"
    },
    {
        "wiki_id": "Vegeta_SSJ_Blue_UR",
        "name": "Vegeta (Super Saiyan God SS)",
        "title": "Unparalleled Saiyan Pride",
        "full_name": "Unparalleled Saiyan Pride Vegeta (Super Saiyan God SS)",
        "rarity": "UR",
        "type": "TEQ",
        "cost": 48,
        "hp_max": 14375,
        "atk_max": 15438,
        "def_max": 8250,
        "leader_skill": "TEQ Type Ki +3, HP & ATK & DEF +120%",
        "super_attack": "Final Flash - Causes immense damage to enemy and lowers ATK & DEF",
        "passive_skill": "Saiyan Elite - ATK & DEF +120%; additional Ki +3 when facing Super-type enemies",
        "categories": "[\"God Ki\", \"Super Saiyan\", \"Vegeta's Family\", \"Rival Duo\", \"Bond of Father and Son\"]",
        "link_skills": "[\"Super Saiyan\", \"Golden Warrior\", \"Prepared for Battle\", \"Royal Lineage\", \"Saiyan Warrior Race\"]",
        "is_lr": False,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Vegeta_(SSGSS)_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1008260_thumb.png/120px-Card_1008260_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1008260_thumb.png/60px-Card_1008260_thumb.png",
        "hp_eza": 17000,
        "atk_eza": 18200,
        "def_eza": 10000,
        "eza_leader_skill": "TEQ Type Ki +3, HP & ATK & DEF +150%",
        "eza_passive_skill": "Saiyan Elite - ATK & DEF +150%; Ki +3 and performs an additional attack",
        "awakening_medals": "[{\"name\": \"SSGSS Vegeta Medal\", \"quantity\": 30}, {\"name\": \"Beerus Medal\", \"quantity\": 10}]"
    },
    {
        "wiki_id": "Future_Trunks_SSJ_UR",
        "name": "Future Trunks (Super Saiyan)",
        "title": "Sword of Hope",
        "full_name": "Sword of Hope Future Trunks (Super Saiyan)",
        "rarity": "UR",
        "type": "TEQ",
        "cost": 48,
        "hp_max": 13600,
        "atk_max": 14950,
        "def_max": 8100,
        "leader_skill": "TEQ Type Ki +3, HP, ATK & DEF +100%",
        "super_attack": "Burning Attack - Causes immense damage to enemy and greatly lowers DEF",
        "passive_skill": "Unbreakable Hope - Ki +3 and ATK & DEF +100%; additional attack when facing Extreme-type enemies",
        "categories": "[\"Future Saga\", \"Hybrid Saiyans\", \"Super Saiyan\", \"Time Travelers\", \"Bond of Master and Disciple\"]",
        "link_skills": "[\"Super Saiyan\", \"Prepared for Battle\", \"Z Fighters\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Future_Trunks_(Super_Saiyan)_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1005760_thumb.png/120px-Card_1005760_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1005760_thumb.png/60px-Card_1005760_thumb.png",
        "awakening_medals": "[{\"name\": \"Future Trunks Medal\", \"quantity\": 30}]"
    },
    {
        "wiki_id": "Whis_UR",
        "name": "Whis",
        "title": "Universe 7 Angel",
        "full_name": "Universe 7 Angel Whis",
        "rarity": "UR",
        "type": "TEQ",
        "cost": 45,
        "hp_max": 13800,
        "atk_max": 14500,
        "def_max": 8500,
        "leader_skill": "TEQ Type Ki +3, HP, ATK & DEF +100%",
        "super_attack": "Wis Wis - Causes immense damage to all enemies and raises DEF",
        "passive_skill": "Attendant to God - ATK & DEF +100%; recovers 5% HP at the end of each turn",
        "categories": "[\"God Ki\", \"Realm of Gods\", \"Universe 7\"]",
        "link_skills": "[\"Godly Power\", \"Prepared for Battle\", \"Power Bestowed by God\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Whis_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1008160_thumb.png/120px-Card_1008160_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1008160_thumb.png/60px-Card_1008160_thumb.png"
    },
    {
        "wiki_id": "Hit_UR",
        "name": "Hit",
        "title": "Legendary Assassin",
        "full_name": "Legendary Assassin Hit",
        "rarity": "UR",
        "type": "INT",
        "cost": 48,
        "hp_max": 13200,
        "atk_max": 14600,
        "def_max": 8800,
        "leader_skill": "INT Type Ki +3, HP, ATK & DEF +100%",
        "super_attack": "Time-Skip/Onslaught - Causes immense damage to enemy and greatly lowers ATK",
        "passive_skill": "Time Manipulation - ATK +120%; Ki +3 when HP is 80% or above",
        "categories": "[\"Universe 6\", \"Tournament of Power\", \"Gifted Warriors\", \"Shocking Speed\"]",
        "link_skills": "[\"Universe's Most Powerful\", \"Prepared for Battle\", \"Shocking Speed\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Hit_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1011060_thumb.png/120px-Card_1011060_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1011060_thumb.png/60px-Card_1011060_thumb.png",
        "hp_eza": 15600,
        "atk_eza": 17300,
        "def_eza": 10500,
        "eza_leader_skill": "INT Type Ki +3, HP, ATK & DEF +130%",
        "eza_passive_skill": "Time Manipulation - ATK +150%; Ki +3 and stuns enemy with a low chance",
        "awakening_medals": "[{\"name\": \"Hit Medal\", \"quantity\": 30}]"
    },
    {
        "wiki_id": "Piccolo_Awakening_UR",
        "name": "Piccolo (Power Awakening)",
        "title": "Hidden Awakening",
        "full_name": "Hidden Awakening Piccolo (Power Awakening)",
        "rarity": "UR",
        "type": "INT",
        "cost": 48,
        "hp_max": 13800,
        "atk_max": 14200,
        "def_max": 9000,
        "leader_skill": "INT Type Ki +3, HP, ATK & DEF +100%",
        "super_attack": "Special Beam Cannon - Causes immense damage to enemy and raises DEF",
        "passive_skill": "Namekian Power - ATK & DEF +100%; Ki +3 when facing Super-type enemies",
        "categories": "[\"Namekians\", \"Goku's Family\", \"Bond of Master and Disciple\", \"Galactic Patrol\"]",
        "link_skills": "[\"Namekian\", \"Prepared for Battle\", \"Z Fighters\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Piccolo_(Power_Awakening)_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1018900_thumb.png/120px-Card_1018900_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1018900_thumb.png/60px-Card_1018900_thumb.png",
        "is_transformable": True,
        "transformation_conditions": "Can transform when HP is 50% or below after receiving a hit"
    },
    {
        "wiki_id": "Android_17_UR",
        "name": "Android 17",
        "title": "Defiant Cell Destroyer",
        "full_name": "Defiant Cell Destroyer Android 17",
        "rarity": "UR",
        "type": "INT",
        "cost": 48,
        "hp_max": 13400,
        "atk_max": 14700,
        "def_max": 8600,
        "leader_skill": "INT Type Ki +3, HP, ATK & DEF +100%",
        "super_attack": "Accel Dance - Causes immense damage to enemy",
        "passive_skill": "Infinite Energy - ATK & DEF +100%; Ki +3 per INT Ki Sphere obtained",
        "categories": "[\"Androids/Cell Saga\", \"Tournament of Power\", \"Artificial Life Forms\", \"Universe 7\"]",
        "link_skills": "[\"Androids\", \"Prepared for Battle\", \"Fierce Battle\", \"Shattering the Limit\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Android_17_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1012160_thumb.png/120px-Card_1012160_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1012160_thumb.png/60px-Card_1012160_thumb.png",
        "awakening_medals": "[{\"name\": \"Android 17 Medal\", \"quantity\": 30}]"
    },
    {
        "wiki_id": "Majin_Vegeta_UR",
        "name": "Majin Vegeta",
        "title": "Unfading Pride",
        "full_name": "Unfading Pride Majin Vegeta",
        "rarity": "UR",
        "type": "STR",
        "cost": 48,
        "hp_max": 14000,
        "atk_max": 15200,
        "def_max": 7800,
        "leader_skill": "STR Type Ki +3, HP & ATK & DEF +100%",
        "super_attack": "Final Explosion - Causes immense damage to all enemies",
        "passive_skill": "Majin Power - ATK +120%; Ki +3 and ATK +20% per PHY Ki Sphere obtained",
        "categories": "[\"Majin Buu Saga\", \"Vegeta's Family\", \"Pure Saiyans\", \"Rival Duo\", \"Bond of Father and Son\"]",
        "link_skills": "[\"Super Saiyan\", \"Golden Warrior\", \"Prepared for Battle\", \"Royal Lineage\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Majin_Vegeta_STR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1004760_thumb.png/120px-Card_1004760_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1004760_thumb.png/60px-Card_1004760_thumb.png",
        "hp_eza": 16500,
        "atk_eza": 18000,
        "def_eza": 9700,
        "eza_leader_skill": "STR Type Ki +3, HP & ATK & DEF +130%",
        "eza_passive_skill": "Majin Power - ATK +150%; Ki +3 and ATK +30% per PHY Ki Sphere obtained",
        "awakening_medals": "[{\"name\": \"Majin Vegeta Medal\", \"quantity\": 30}, {\"name\": \"Babidi Medal\", \"quantity\": 15}]"
    },
    {
        "wiki_id": "Broly_LSS_UR",
        "name": "Broly (Legendary Super Saiyan)",
        "title": "Unparalleled Berserker",
        "full_name": "Unparalleled Berserker Broly (Legendary Super Saiyan)",
        "rarity": "UR",
        "type": "STR",
        "cost": 48,
        "hp_max": 14500,
        "atk_max": 15800,
        "def_max": 7500,
        "leader_skill": "STR Type Ki +3, HP & ATK & DEF +100%",
        "super_attack": "Omega Blaster - Causes immense damage to all enemies",
        "passive_skill": "Berserker Power - ATK +150% when performing a Super Attack; HP +1000",
        "categories": "[\"Pure Saiyans\", \"Movie Heroes\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Super Saiyan\", \"Prepared for Battle\", \"Brutal Beatdown\", \"Saiyan Warrior Race\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Broly_(LSS)_STR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1003160_thumb.png/120px-Card_1003160_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1003160_thumb.png/60px-Card_1003160_thumb.png",
        "awakening_medals": "[{\"name\": \"Legendary Super Saiyan Medal\", \"quantity\": 30}]"
    },
    {
        "wiki_id": "Super_Janemba_UR",
        "name": "Super Janemba",
        "title": "Bizarre Demonic Transformation",
        "full_name": "Bizarre Demonic Transformation Super Janemba",
        "rarity": "UR",
        "type": "PHY",
        "cost": 48,
        "hp_max": 13600,
        "atk_max": 14900,
        "def_max": 8200,
        "leader_skill": "PHY Type Ki +3, HP & ATK & DEF +100%",
        "super_attack": "Illusion Smash - Causes immense damage to enemy and lowers DEF",
        "passive_skill": "Wicked Demon - ATK +120% and DEF +80%; high chance to evade enemy Super Attacks",
        "categories": "[\"Movie Bosses\", \"Wicked Bloodline\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Brutal Beatdown\", \"Prepared for Battle\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Super_Janemba_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1003760_thumb.png/120px-Card_1003760_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1003760_thumb.png/60px-Card_1003760_thumb.png",
        "awakening_medals": "[{\"name\": \"Janemba Medal\", \"quantity\": 30}]"
    },
    {
        "wiki_id": "Frieza_Final_Form_UR",
        "name": "Frieza (Final Form)",
        "title": "Ruler of the Universe",
        "full_name": "Ruler of the Universe Frieza (Final Form)",
        "rarity": "UR",
        "type": "PHY",
        "cost": 48,
        "hp_max": 13100,
        "atk_max": 14300,
        "def_max": 8000,
        "leader_skill": "PHY Type Ki +3, HP & ATK & DEF +100%",
        "super_attack": "Death Ball - Causes immense damage to enemy and greatly lowers DEF",
        "passive_skill": "Universal Domination - Ki +3, ATK +100%; lowers enemy DEF by 10% per attack",
        "categories": "[\"Frieza Saga\", \"Wicked Bloodline\", \"Universe's Most Powerful\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Universe's Most Powerful\", \"Brutal Beatdown\", \"Shocking Speed\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Frieza_(Final_Form)_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001260_thumb.png/120px-Card_1001260_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001260_thumb.png/60px-Card_1001260_thumb.png",
        "hp_eza": 15500,
        "atk_eza": 17000,
        "def_eza": 9700,
        "eza_leader_skill": "PHY Type Ki +3, HP & ATK & DEF +130%",
        "eza_passive_skill": "Universal Domination - Ki +3, ATK +130%; greatly lowers enemy DEF per attack",
        "awakening_medals": "[{\"name\": \"Frieza Medal\", \"quantity\": 30}, {\"name\": \"Cold Family Medal\", \"quantity\": 15}]",
        "is_transformable": True,
        "transformation_conditions": "Can transform when HP is 30% or below"
    },
    {
        "wiki_id": "Super_Saiyan_Goku_SSR",
        "name": "Goku",
        "title": "Super Saiyan",
        "full_name": "Super Saiyan Goku",
        "rarity": "SSR",
        "type": "AGL",
        "cost": 32,
        "hp_max": 9274,
        "atk_max": 8537,
        "def_max": 4901,
        "leader_skill": "AGL Type Ki +3 and HP, ATK & DEF +70%",
        "super_attack": "Kamehameha - Raises ATK & DEF and causes immense damage to enemy",
        "passive_skill": "Golden Warrior - Ki +4 and ATK & DEF +100% when HP is 50% or above",
        "categories": "[\"Super Saiyan\", \"Full Power\", \"Kamehameha\", \"Goku's Family\"]",
        "link_skills": "[\"Super Saiyan\", \"Kamehameha\", \"Golden Warrior\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": True,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Super_Saiyan_Goku_(AGL)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000360_thumb.png/120px-Card_1000360_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000360_thumb.png/60px-Card_1000360_thumb.png",
        "hp_eza": 11000,
        "atk_eza": 10200,
        "def_eza": 6000,
        "eza_leader_skill": "AGL Type Ki +3 and HP, ATK & DEF +100%",
        "eza_passive_skill": "Golden Warrior - Ki +4 and ATK & DEF +130% when HP is 50% or above",
        "awakening_medals": "[{\"name\": \"Super Saiyan Goku Medal\", \"quantity\": 25}, {\"name\": \"AGL Medal\", \"quantity\": 7}]"
    },
    {
        "wiki_id": "SSJ2_Goku_SSR",
        "name": "Goku (Super Saiyan 2)",
        "title": "Eternal Rival",
        "full_name": "Eternal Rival Goku (Super Saiyan 2)",
        "rarity": "SSR",
        "type": "AGL",
        "cost": 32,
        "hp_max": 9500,
        "atk_max": 9000,
        "def_max": 5100,
        "leader_skill": "AGL Type Ki +3 and HP, ATK & DEF +70%",
        "super_attack": "Super Kamehameha - Raises ATK and causes immense damage to enemy",
        "passive_skill": "Unflinching Resolve - ATK & DEF +80% when HP is 80% or above",
        "categories": "[\"Pure Saiyans\", \"Goku's Family\", \"Rival Duo\", \"Full Power\"]",
        "link_skills": "[\"Super Saiyan\", \"Kamehameha\", \"Golden Warrior\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Super_Saiyan_2_Goku_(AGL)",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1005460_thumb.png/120px-Card_1005460_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1005460_thumb.png/60px-Card_1005460_thumb.png",
        "awakening_medals": "[{\"name\": \"SSJ2 Goku Medal\", \"quantity\": 25}]"
    },
    {
        "wiki_id": "SSJ_Trunks_Teen_SSR",
        "name": "Trunks (Teen) (Super Saiyan)",
        "title": "Child of Hope",
        "full_name": "Child of Hope Trunks (Teen) (Super Saiyan)",
        "rarity": "SSR",
        "type": "AGL",
        "cost": 29,
        "hp_max": 8900,
        "atk_max": 8100,
        "def_max": 4700,
        "leader_skill": "AGL Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Burning Attack - Raises ATK and causes immense damage to enemy",
        "passive_skill": "Protecting the Future - ATK +80% when HP is 50% or above",
        "categories": "[\"Future Saga\", \"Hybrid Saiyans\", \"Super Saiyan\", \"Bond of Parent and Child\"]",
        "link_skills": "[\"Super Saiyan\", \"Prepared for Battle\", \"Z Fighters\", \"Shattering the Limit\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Trunks_(Teen)_(Super_Saiyan)_AGL",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1003560_thumb.png/120px-Card_1003560_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1003560_thumb.png/60px-Card_1003560_thumb.png",
        "awakening_medals": "[{\"name\": \"Trunks Medal\", \"quantity\": 25}]"
    },
    {
        "wiki_id": "SSJ_Gohan_Teen_SSR",
        "name": "Gohan (Teen) (Super Saiyan)",
        "title": "Awakening Rage",
        "full_name": "Awakening Rage Gohan (Teen) (Super Saiyan)",
        "rarity": "SSR",
        "type": "TEQ",
        "cost": 29,
        "hp_max": 8600,
        "atk_max": 8900,
        "def_max": 4500,
        "leader_skill": "TEQ Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Soaring Dragon Strike - Raises ATK and causes immense damage to enemy",
        "passive_skill": "Hidden Power - ATK +100% when HP is 80% or above",
        "categories": "[\"Hybrid Saiyans\", \"Goku's Family\", \"Cell Saga\", \"Bond of Parent and Child\"]",
        "link_skills": "[\"Super Saiyan\", \"Prepared for Battle\", \"Z Fighters\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Gohan_(Teen)_(Super_Saiyan)_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1002960_thumb.png/120px-Card_1002960_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1002960_thumb.png/60px-Card_1002960_thumb.png",
        "awakening_medals": "[{\"name\": \"Teen Gohan Medal\", \"quantity\": 25}, {\"name\": \"Cell Medal\", \"quantity\": 10}]"
    },
    {
        "wiki_id": "Android_18_SSR",
        "name": "Android 18",
        "title": "Beautiful Warrior",
        "full_name": "Beautiful Warrior Android 18",
        "rarity": "SSR",
        "type": "TEQ",
        "cost": 29,
        "hp_max": 8200,
        "atk_max": 8500,
        "def_max": 5000,
        "leader_skill": "TEQ Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Accel Dance - Causes immense damage to enemy",
        "passive_skill": "Android Energy - ATK & DEF +80%; Ki +3 per TEQ Ki Sphere obtained",
        "categories": "[\"Androids/Cell Saga\", \"Artificial Life Forms\", \"Resurrected Warriors\"]",
        "link_skills": "[\"Androids\", \"Prepared for Battle\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Android_18_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1004460_thumb.png/120px-Card_1004460_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1004460_thumb.png/60px-Card_1004460_thumb.png",
        "awakening_medals": "[{\"name\": \"Android 18 Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "SSJ_Vegeta_SSR",
        "name": "Vegeta (Super Saiyan)",
        "title": "Saiyan Prince",
        "full_name": "Saiyan Prince Vegeta (Super Saiyan)",
        "rarity": "SSR",
        "type": "TEQ",
        "cost": 29,
        "hp_max": 8800,
        "atk_max": 9100,
        "def_max": 4600,
        "leader_skill": "TEQ Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Galick Gun - Causes immense damage to enemy and lowers ATK & DEF",
        "passive_skill": "Royal Bloodline - ATK +80% and Ki +3 when facing Super-type enemies",
        "categories": "[\"Pure Saiyans\", \"Vegeta's Family\", \"Super Saiyan\", \"Rival Duo\"]",
        "link_skills": "[\"Super Saiyan\", \"Royal Lineage\", \"Golden Warrior\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Vegeta_(Super_Saiyan)_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001460_thumb.png/120px-Card_1001460_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001460_thumb.png/60px-Card_1001460_thumb.png",
        "awakening_medals": "[{\"name\": \"SSJ Vegeta Medal\", \"quantity\": 25}]"
    },
    {
        "wiki_id": "Piccolo_SSR",
        "name": "Piccolo",
        "title": "Namekian Warrior",
        "full_name": "Namekian Warrior Piccolo",
        "rarity": "SSR",
        "type": "INT",
        "cost": 29,
        "hp_max": 8400,
        "atk_max": 7900,
        "def_max": 5200,
        "leader_skill": "INT Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Special Beam Cannon - Causes immense damage to enemy and raises DEF",
        "passive_skill": "Warrior's Pride - DEF +80%; Ki +3 when HP is 70% or above",
        "categories": "[\"Namekians\", \"Bond of Master and Disciple\", \"Z Fighters\"]",
        "link_skills": "[\"Namekian\", \"Prepared for Battle\", \"Z Fighters\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Piccolo_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001660_thumb.png/120px-Card_1001660_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001660_thumb.png/60px-Card_1001660_thumb.png",
        "awakening_medals": "[{\"name\": \"Piccolo Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "Captain_Ginyu_SSR",
        "name": "Captain Ginyu",
        "title": "Ginyu Force Captain",
        "full_name": "Ginyu Force Captain Captain Ginyu",
        "rarity": "SSR",
        "type": "INT",
        "cost": 29,
        "hp_max": 8100,
        "atk_max": 7700,
        "def_max": 5000,
        "leader_skill": "INT Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Body Change - Causes immense damage (special effect)",
        "passive_skill": "Ginyu Force - ATK +80% when HP is 50% or above; reduces damage by 15%",
        "categories": "[\"Frieza Saga\", \"Wicked Bloodline\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Prepared for Battle\", \"Brutal Beatdown\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Captain_Ginyu_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1002060_thumb.png/120px-Card_1002060_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1002060_thumb.png/60px-Card_1002060_thumb.png",
        "awakening_medals": "[{\"name\": \"Ginyu Force Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "SSJ2_Vegeta_SSR",
        "name": "Vegeta (Super Saiyan 2)",
        "title": "Awakened Warrior",
        "full_name": "Awakened Warrior Vegeta (Super Saiyan 2)",
        "rarity": "SSR",
        "type": "STR",
        "cost": 29,
        "hp_max": 8700,
        "atk_max": 9200,
        "def_max": 4800,
        "leader_skill": "STR Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Final Flash - Causes immense damage to enemy and lowers ATK & DEF",
        "passive_skill": "Saiyan Elitism - ATK +80% and Ki +3 when HP is 80% or above",
        "categories": "[\"Pure Saiyans\", \"Vegeta's Family\", \"Super Saiyan 2\", \"Majin Buu Saga\"]",
        "link_skills": "[\"Super Saiyan\", \"Golden Warrior\", \"Prepared for Battle\", \"Royal Lineage\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Vegeta_(Super_Saiyan_2)_STR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1006260_thumb.png/120px-Card_1006260_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1006260_thumb.png/60px-Card_1006260_thumb.png",
        "awakening_medals": "[{\"name\": \"SSJ2 Vegeta Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "Nappa_SSR",
        "name": "Nappa",
        "title": "Elite Saiyan Warrior",
        "full_name": "Elite Saiyan Warrior Nappa",
        "rarity": "SSR",
        "type": "STR",
        "cost": 24,
        "hp_max": 8300,
        "atk_max": 8600,
        "def_max": 4300,
        "leader_skill": "STR Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Giant Storm - Causes immense damage to all enemies",
        "passive_skill": "Saiyan Pride - ATK +70% when HP is 50% or above",
        "categories": "[\"Saiyan Saga\", \"Pure Saiyans\", \"Terrifying Conquerors\", \"Wicked Bloodline\"]",
        "link_skills": "[\"Prepared for Battle\", \"Saiyan Warrior Race\", \"Brutal Beatdown\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Nappa_STR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001060_thumb.png/120px-Card_1001060_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001060_thumb.png/60px-Card_1001060_thumb.png",
        "awakening_medals": "[{\"name\": \"Nappa Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "Frieza_100_Full_Power_SSR",
        "name": "Frieza (100% Full Power)",
        "title": "Legendary Conqueror",
        "full_name": "Legendary Conqueror Frieza (100% Full Power)",
        "rarity": "SSR",
        "type": "PHY",
        "cost": 29,
        "hp_max": 8000,
        "atk_max": 9100,
        "def_max": 4600,
        "leader_skill": "PHY Type Ki +3 and HP, ATK & DEF +50%",
        "super_attack": "Supernova - Causes immense damage to enemy",
        "passive_skill": "Maximum Power - ATK +100% when HP is 80% or above",
        "categories": "[\"Frieza Saga\", \"Wicked Bloodline\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Universe's Most Powerful\", \"Brutal Beatdown\", \"Shocking Speed\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Frieza_(100_Full_Power)_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001760_thumb.png/120px-Card_1001760_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001760_thumb.png/60px-Card_1001760_thumb.png",
        "awakening_medals": "[{\"name\": \"Frieza Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "Zarbon_Transformed_SSR",
        "name": "Zarbon (Post-Transformation)",
        "title": "Gruesome Transformation",
        "full_name": "Gruesome Transformation Zarbon (Post-Transformation)",
        "rarity": "SSR",
        "type": "PHY",
        "cost": 24,
        "hp_max": 7700,
        "atk_max": 8200,
        "def_max": 4400,
        "leader_skill": "PHY Type Ki +3 and HP, ATK & DEF +40%",
        "super_attack": "Beautiful Devastation - Causes immense damage to enemy and raises ATK",
        "passive_skill": "Monster's Beauty - ATK +70% when performing a Super Attack",
        "categories": "[\"Frieza Saga\", \"Wicked Bloodline\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Brutal Beatdown\", \"Prepared for Battle\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Zarbon_(Post-Transformation)_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001960_thumb.png/120px-Card_1001960_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001960_thumb.png/60px-Card_1001960_thumb.png",
        "awakening_medals": "[{\"name\": \"Zarbon Medal\", \"quantity\": 20}]"
    },
    {
        "wiki_id": "Goku_GT_SR",
        "name": "Goku (GT)",
        "title": "Youthful Challenger",
        "full_name": "Youthful Challenger Goku (GT)",
        "rarity": "SR",
        "type": "AGL",
        "cost": 18,
        "hp_max": 6800,
        "atk_max": 7100,
        "def_max": 3500,
        "leader_skill": "AGL Type Ki +2 and HP, ATK & DEF +30%",
        "super_attack": "Dragon Fist - Raises ATK and causes big damage to enemy",
        "passive_skill": "Tail of Tenacity - Ki +3 per AGL Ki Sphere obtained",
        "categories": "[\"Goku's Family\", \"Pure Saiyans\", \"GT Heroes\"]",
        "link_skills": "[\"Prepared for Battle\", \"Golden Warrior\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_(GT)_AGL",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1006860_thumb.png/120px-Card_1006860_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1006860_thumb.png/60px-Card_1006860_thumb.png"
    },
    {
        "wiki_id": "Krillin_SR",
        "name": "Krillin",
        "title": "Earthling's Pride",
        "full_name": "Earthling's Pride Krillin",
        "rarity": "SR",
        "type": "AGL",
        "cost": 14,
        "hp_max": 6100,
        "atk_max": 6000,
        "def_max": 3600,
        "leader_skill": "AGL Type Ki +2 and HP, ATK & DEF +25%",
        "super_attack": "Destructo-Disc - Raises DEF and causes big damage to enemy",
        "passive_skill": "Z Fighter's Spirit - ATK +50% when HP is 70% or above",
        "categories": "[\"Turtle School\", \"Z Fighters\", \"Earthlings\"]",
        "link_skills": "[\"Turtle School\", \"Prepared for Battle\", \"Z Fighters\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Krillin_AGL",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000460_thumb.png/120px-Card_1000460_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000460_thumb.png/60px-Card_1000460_thumb.png"
    },
    {
        "wiki_id": "Beerus_SR",
        "name": "Beerus",
        "title": "Wrathful God of Destruction",
        "full_name": "Wrathful God of Destruction Beerus",
        "rarity": "SR",
        "type": "TEQ",
        "cost": 18,
        "hp_max": 6500,
        "atk_max": 7200,
        "def_max": 3300,
        "leader_skill": "TEQ Type Ki +2 and HP, ATK & DEF +30%",
        "super_attack": "God of Destruction's Wrath - Raises ATK and causes big damage to all enemies",
        "passive_skill": "Sealable Power - ATK +60%; medium chance to seal attacked enemy Super Attack",
        "categories": "[\"God Ki\", \"Realm of Gods\", \"Universe 7\"]",
        "link_skills": "[\"Godly Power\", \"Prepared for Battle\", \"Shattering the Limit\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Beerus_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1007860_thumb.png/120px-Card_1007860_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1007860_thumb.png/60px-Card_1007860_thumb.png"
    },
    {
        "wiki_id": "Goten_SR",
        "name": "Goten",
        "title": "Mini Kamehameha",
        "full_name": "Mini Kamehameha Goten",
        "rarity": "SR",
        "type": "TEQ",
        "cost": 14,
        "hp_max": 5900,
        "atk_max": 5800,
        "def_max": 3200,
        "leader_skill": "TEQ Type Ki +2 and HP, ATK & DEF +20%",
        "super_attack": "Kamehameha - Causes big damage to enemy",
        "passive_skill": "Mini Power-Up - ATK +40% when performing a Super Attack",
        "categories": "[\"Goku's Family\", \"Hybrid Saiyans\", \"Turtle School\"]",
        "link_skills": "[\"Super Saiyan\", \"Kamehameha\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goten_TEQ",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1004860_thumb.png/120px-Card_1004860_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1004860_thumb.png/60px-Card_1004860_thumb.png"
    },
    {
        "wiki_id": "Tien_Shinhan_SR",
        "name": "Tien Shinhan",
        "title": "Pursuing the Pinnacle",
        "full_name": "Pursuing the Pinnacle Tien Shinhan",
        "rarity": "SR",
        "type": "INT",
        "cost": 16,
        "hp_max": 6200,
        "atk_max": 6400,
        "def_max": 3700,
        "leader_skill": "INT Type Ki +2 and HP, ATK & DEF +25%",
        "super_attack": "Tri-Beam - Causes big damage to enemy",
        "passive_skill": "Indomitable Warrior - ATK +50% when HP is 50% or above",
        "categories": "[\"Crane School\", \"Z Fighters\", \"Earthlings\"]",
        "link_skills": "[\"Crane School\", \"Prepared for Battle\", \"Z Fighters\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Tien_Shinhan_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000860_thumb.png/120px-Card_1000860_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000860_thumb.png/60px-Card_1000860_thumb.png"
    },
    {
        "wiki_id": "Kid_Buu_SR",
        "name": "Kid Buu",
        "title": "Savage Destruction",
        "full_name": "Savage Destruction Kid Buu",
        "rarity": "SR",
        "type": "INT",
        "cost": 20,
        "hp_max": 7200,
        "atk_max": 7600,
        "def_max": 3600,
        "leader_skill": "INT Type Ki +2 and HP, ATK & DEF +30%",
        "super_attack": "Planet Burst - Causes big damage to all enemies",
        "passive_skill": "Onslaught - ATK +60% when HP is 80% or above",
        "categories": "[\"Majin Buu Saga\", \"Wicked Bloodline\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Prepared for Battle\", \"Brutal Beatdown\", \"Fierce Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Kid_Buu_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1006060_thumb.png/120px-Card_1006060_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1006060_thumb.png/60px-Card_1006060_thumb.png"
    },
    {
        "wiki_id": "Raditz_SR",
        "name": "Raditz",
        "title": "Invading Warrior",
        "full_name": "Invading Warrior Raditz",
        "rarity": "SR",
        "type": "STR",
        "cost": 16,
        "hp_max": 6400,
        "atk_max": 7000,
        "def_max": 3200,
        "leader_skill": "STR Type Ki +2 and HP, ATK & DEF +25%",
        "super_attack": "Saturday Crush - Raises ATK and causes big damage to enemy",
        "passive_skill": "Saiyan's Power - ATK +50% when performing a Super Attack",
        "categories": "[\"Saiyan Saga\", \"Pure Saiyans\", \"Wicked Bloodline\", \"Bond of Parent and Child\"]",
        "link_skills": "[\"Prepared for Battle\", \"Saiyan Warrior Race\", \"Brutal Beatdown\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Raditz_STR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000760_thumb.png/120px-Card_1000760_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000760_thumb.png/60px-Card_1000760_thumb.png"
    },
    {
        "wiki_id": "Bardock_SR",
        "name": "Bardock",
        "title": "Fearless Spirit",
        "full_name": "Fearless Spirit Bardock",
        "rarity": "SR",
        "type": "PHY",
        "cost": 16,
        "hp_max": 6300,
        "atk_max": 6800,
        "def_max": 3300,
        "leader_skill": "PHY Type Ki +2 and HP, ATK & DEF +25%",
        "super_attack": "Riot Javelin - Causes big damage to enemy",
        "passive_skill": "Proof of His Revival - ATK +50% when HP is 80% or above",
        "categories": "[\"Pure Saiyans\", \"Saiyan Saga\", \"Bond of Parent and Child\", \"Otherworld Warriors\"]",
        "link_skills": "[\"Prepared for Battle\", \"Saiyan Warrior Race\", \"Z Fighters\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Bardock_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000960_thumb.png/120px-Card_1000960_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000960_thumb.png/60px-Card_1000960_thumb.png"
    },
    {
        "wiki_id": "Dodoria_SR",
        "name": "Dodoria",
        "title": "Frieza's Henchman",
        "full_name": "Frieza's Henchman Dodoria",
        "rarity": "SR",
        "type": "PHY",
        "cost": 14,
        "hp_max": 5600,
        "atk_max": 6200,
        "def_max": 3000,
        "leader_skill": "PHY Type Ki +2 and HP, ATK & DEF +20%",
        "super_attack": "Dodoria Beam - Causes big damage to enemy",
        "passive_skill": "Brute Force - ATK +50% when HP is 50% or above",
        "categories": "[\"Frieza Saga\", \"Wicked Bloodline\", \"Terrifying Conquerors\"]",
        "link_skills": "[\"Brutal Beatdown\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Dodoria_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001860_thumb.png/120px-Card_1001860_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1001860_thumb.png/60px-Card_1001860_thumb.png"
    },
    {
        "wiki_id": "Goku_Saiyan_Saga_R",
        "name": "Goku",
        "title": "Saiyan Raised on Earth",
        "full_name": "Saiyan Raised on Earth Goku",
        "rarity": "R",
        "type": "AGL",
        "cost": 11,
        "hp_max": 4800,
        "atk_max": 5200,
        "def_max": 2500,
        "leader_skill": "AGL Type Ki +1 and HP, ATK & DEF +15%",
        "super_attack": "Kamehameha - Causes damage to enemy",
        "passive_skill": "Saiyan Lineage - Ki +2 at the start of each turn",
        "categories": "[\"Saiyan Saga\", \"Pure Saiyans\", \"Goku's Family\"]",
        "link_skills": "[\"Kamehameha\", \"Prepared for Battle\", \"Z Fighters\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_AGL_R",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000160_thumb.png/120px-Card_1000160_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000160_thumb.png/60px-Card_1000160_thumb.png"
    },
    {
        "wiki_id": "Yamcha_R",
        "name": "Yamcha",
        "title": "Wolf Fang Fighter",
        "full_name": "Wolf Fang Fighter Yamcha",
        "rarity": "R",
        "type": "AGL",
        "cost": 8,
        "hp_max": 4200,
        "atk_max": 4500,
        "def_max": 2200,
        "leader_skill": "AGL Type Ki +1 and HP, ATK & DEF +10%",
        "super_attack": "Wolf Fang Fist - Causes damage to enemy",
        "passive_skill": "Desert Bandit - Ki +1 when HP is 80% or above",
        "categories": "[\"Turtle School\", \"Z Fighters\", \"Earthlings\"]",
        "link_skills": "[\"Turtle School\", \"Prepared for Battle\", \"Z Fighters\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Yamcha_AGL",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000660_thumb.png/120px-Card_1000660_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000660_thumb.png/60px-Card_1000660_thumb.png"
    },
    {
        "wiki_id": "Recoome_R",
        "name": "Recoome",
        "title": "Ginyu Force Member",
        "full_name": "Ginyu Force Member Recoome",
        "rarity": "R",
        "type": "STR",
        "cost": 10,
        "hp_max": 4900,
        "atk_max": 5600,
        "def_max": 2200,
        "leader_skill": "STR Type Ki +1 and HP, ATK & DEF +10%",
        "super_attack": "Recoome Eraser Gun - Causes damage to enemy",
        "passive_skill": "Ginyu Force Pride - ATK +30% when HP is 80% or above",
        "categories": "[\"Frieza Saga\", \"Wicked Bloodline\"]",
        "link_skills": "[\"Prepared for Battle\", \"Brutal Beatdown\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Recoome_STR",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1002260_thumb.png/120px-Card_1002260_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1002260_thumb.png/60px-Card_1002260_thumb.png"
    },
    {
        "wiki_id": "Tenshinhan_R",
        "name": "Tenshinhan",
        "title": "Crane Warrior",
        "full_name": "Crane Warrior Tenshinhan",
        "rarity": "R",
        "type": "INT",
        "cost": 8,
        "hp_max": 4200,
        "atk_max": 4600,
        "def_max": 2300,
        "leader_skill": "INT Type Ki +1 and HP, ATK & DEF +10%",
        "super_attack": "Tri-Beam - Causes damage to enemy",
        "passive_skill": "Crane School Training - ATK +25% when HP is 70% or above",
        "categories": "[\"Crane School\", \"Z Fighters\", \"Earthlings\"]",
        "link_skills": "[\"Crane School\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Tenshinhan_INT",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000560_thumb.png/120px-Card_1000560_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000560_thumb.png/60px-Card_1000560_thumb.png"
    },
    {
        "wiki_id": "Gohan_Kid_N",
        "name": "Gohan (Kid)",
        "title": "Gentle-Hearted Warrior",
        "full_name": "Gentle-Hearted Warrior Gohan (Kid)",
        "rarity": "N",
        "type": "PHY",
        "cost": 5,
        "hp_max": 3200,
        "atk_max": 3000,
        "def_max": 1800,
        "leader_skill": "PHY Type Ki +1",
        "super_attack": "Masenko - Causes some damage to enemy",
        "passive_skill": "Hidden Power - ATK +20% when HP is 50% or above",
        "categories": "[\"Goku's Family\", \"Hybrid Saiyans\", \"Z Fighters\"]",
        "link_skills": "[\"Prepared for Battle\", \"Z Fighters\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Gohan_(Kid)_PHY",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000960_thumb.png/120px-Card_1000960_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000960_thumb.png/60px-Card_1000960_thumb.png"
    },
    {
        "wiki_id": "Goku_Base_N",
        "name": "Goku",
        "title": "Earth's Greatest Hero",
        "full_name": "Earth's Greatest Hero Goku",
        "rarity": "N",
        "type": "AGL",
        "cost": 5,
        "hp_max": 3000,
        "atk_max": 3200,
        "def_max": 1700,
        "leader_skill": "AGL Type Ki +1",
        "super_attack": "Kamehameha - Causes some damage to enemy",
        "passive_skill": "Saiyan Spirit - Ki +1 per AGL Ki Sphere obtained",
        "categories": "[\"Goku's Family\", \"Pure Saiyans\", \"Z Fighters\"]",
        "link_skills": "[\"Kamehameha\", \"Prepared for Battle\"]",
        "is_lr": False,
        "is_eza": False,
        "is_dokkan_fest": False,
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Goku_AGL_N",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000060_thumb.png/120px-Card_1000060_thumb.png",
        "thumb_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/thumb/Card_1000060_thumb.png/60px-Card_1000060_thumb.png"
    }
]

# ===========================================================================
#  EVENTOS DE EJEMPLO
# ===========================================================================

SAMPLE_EVENTS = [
    {
        "name": "The Chosen Super Warriors",
        "description": "Battle against Goku, Vegeta and their allies in this multi-stage event.",
        "event_type": "Story",
        "difficulty": "Z-Hard",
        "start_date": "2024-01-01T00:00:00",
        "end_date": "2024-12-31T23:59:59",
        "stages": 10,
        "stamina_cost": 25,
        "rewards": json.dumps(["Awakening Medal", "Dragon Stone x3", "Zeni x100000"]),
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/The_Chosen_Super_Warriors",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/Event_chosen_super_warriors.png",
    },
    {
        "name": "Extreme Z-Battle: Super Saiyan Gohan (Youth)",
        "description": "An extreme challenge featuring Super Saiyan Gohan. Complete to unlock EZA.",
        "event_type": "EZB",
        "difficulty": "Super2",
        "start_date": "2024-06-01T00:00:00",
        "end_date": "2024-06-30T23:59:59",
        "stages": 7,
        "stamina_cost": 30,
        "rewards": json.dumps(["EZA Medals", "Dragon Stone x5"]),
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Extreme_Z-Battle_Gohan",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/EZB_Gohan.png",
    },
]

# ===========================================================================
#  BANNERS DE EJEMPLO
# ===========================================================================

SAMPLE_BANNERS = [
    {
        "name": "Dokkan Festival: Ultra Instinct Goku",
        "description": "Celebrate the power of Ultra Instinct with this special Dokkan Festival summon.",
        "banner_type": "DF",
        "start_date": "2024-03-01T00:00:00",
        "end_date": "2024-03-15T23:59:59",
        "featured_cards": json.dumps(["Ultra Instinct Goku", "Gohan (Beast)"]),
        "summon_rates": json.dumps({"LR": "0.5%", "UR": "5%", "SSR": "15%"}),
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Dokkan_Festival_UI_Goku",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/Banner_UI_Goku_DF.png",
    },
    {
        "name": "Legendary Summon: Pure Saiyans",
        "description": "Summon Pure Saiyan warriors including Super Saiyan Goku and Vegeta.",
        "banner_type": "Normal",
        "start_date": "2024-01-15T00:00:00",
        "end_date": "2024-02-14T23:59:59",
        "featured_cards": json.dumps(["Super Saiyan Goku", "Super Saiyan Vegeta", "Bardock"]),
        "summon_rates": json.dumps({"UR": "7%", "SSR": "20%"}),
        "wiki_url": "https://dbz-dokkanbattle.fandom.com/wiki/Legendary_Summon_Pure_Saiyans",
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/Banner_Pure_Saiyans.png",
    },
]

# ===========================================================================
#  ITEMS DE EJEMPLO
# ===========================================================================

SAMPLE_ITEMS = [
    {
        "name": "Dragon Stone",
        "description": "A rare stone imbued with the power of the Dragon Balls. Used to perform summons.",
        "item_type": "Currency",
        "effect": "Perform 1 summon or restore all stamina",
        "rarity": "Rare",
        "how_to_obtain": json.dumps(["Login bonus", "Event reward", "Mission reward", "Real-money purchase"]),
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/Dragon_Stone.png",
    },
    {
        "name": "Senzu Bean",
        "description": "A magical bean that fully restores HP and Ki in battle.",
        "item_type": "Battle Item",
        "effect": "Fully restores HP and Ki",
        "rarity": "Uncommon",
        "how_to_obtain": json.dumps(["Event reward", "Mission reward", "Shop purchase"]),
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/Senzu_Bean.png",
    },
    {
        "name": "Bulma's Scouter",
        "description": "An item that reveals enemy information.",
        "item_type": "Battle Item",
        "effect": "Reveals enemy HP and ATK information",
        "rarity": "Common",
        "how_to_obtain": json.dumps(["Event reward", "Zeni Shop"]),
        "image_url": "https://static.wikia.nocookie.net/dbz-dokkanbattle/images/Bulma_Scouter.png",
    },
]


# ===========================================================================
#  FUNCIONES DE SEED
# ===========================================================================

def seed_cards(db):
    count = 0
    for data in SAMPLE_CARDS:
        existing = db.query(Card).filter(Card.wiki_id == data.get("wiki_id")).first()
        if not existing:
            card = Card(**data)
            db.add(card)
            count += 1
    db.commit()
    return count


def seed_events(db):
    count = 0
    for data in SAMPLE_EVENTS:
        existing = db.query(Event).filter(Event.name == data["name"]).first()
        if not existing:
            event = Event(**data)
            db.add(event)
            count += 1
    db.commit()
    return count


def seed_banners(db):
    count = 0
    for data in SAMPLE_BANNERS:
        existing = db.query(Banner).filter(Banner.name == data["name"]).first()
        if not existing:
            banner = Banner(**data)
            db.add(banner)
            count += 1
    db.commit()
    return count


def seed_items(db):
    count = 0
    for data in SAMPLE_ITEMS:
        existing = db.query(Item).filter(Item.name == data["name"]).first()
        if not existing:
            item = Item(**data)
            db.add(item)
            count += 1
    db.commit()
    return count


def main():
    print("Inicializando base de datos...")
    init_db()

    db = SessionLocal()
    try:
        cards_added   = seed_cards(db)
        events_added  = seed_events(db)
        banners_added = seed_banners(db)
        items_added   = seed_items(db)

        print(f"  Cartas insertadas   : {cards_added}")
        print(f"  Eventos insertados  : {events_added}")
        print(f"  Banners insertados  : {banners_added}")
        print(f"  Items insertados    : {items_added}")
        print("Seed completado exitosamente.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
